// 自证能红（H104）：逐处把实现拆掉，确认对应判据真的翻红；跑完一律还原。
// 不做这一步，「6 项通过」可能只是因为判据压根没碰到那段代码——今天已经栽过两次
// （监制台禁写区只验了 19 项里的 7 项；CRLF 跨行锚点静默不匹配）。
const fs = require('fs');
const cp = require('child_process');
const path = require('path');
const 根 = path.join(__dirname, '..');

const 变异 = [
  { 名: 'C1 抽掉 published_at 字段映射', 档: 'intel/adapters/rss.js',
    找: "      published_at: 时刻(it.pubDate != null ? it.pubDate",
    换: "      published_at: null && 时刻(it.pubDate != null ? it.pubDate" },
  // 锚点要打在**真正处理「没有 pubDate 节点」的那一行**上。
  // 上一版打在 `Number.isNaN(t) ? null : ...`，可空字符串在更前面就被 `if (!raw) return null` 截住，
  // 根本走不到那行——变异因此无效，却看着像「判据没红」。锚点没打中病灶时，
  // 得到的是假阴性，跟判据不合格长得一模一样。
  { 名: 'C1 无日期条目改成拿抓取时刻冒充', 档: 'intel/adapters/rss.js',
    找: '  if (!raw) return null;',
    换: '  if (!raw) return new Date().toISOString();' },
  { 名: 'C2 URL 规范化不再削 utm', 档: 'intel/dedupe.js',
    找: '  for (const [k, v] of x.searchParams) if (!追踪参数.test(k)) keep.push([k, v]);',
    换: '  for (const [k, v] of x.searchParams) keep.push([k, v]);' },
  { 名: 'C2 规范化把真定位参数也削掉（反向病）', 档: 'intel/dedupe.js',
    找: '  x.search = keep.length ?',
    换: '  keep.length = 0; x.search = keep.length ?' },
  { 名: 'C3 评分引擎不读配置（写死权重）', 档: 'intel/scoring.js',
    找: '  const AB入 = AB.slice(0, cfg.入选.AB档topN);',
    换: '  const AB入 = AB.slice(0, 12);' },
  { 名: 'C3 S 档不再降门槛全入', 档: 'intel/scoring.js',
    找: "  const S入 = 打过.filter((x) => x.tier === 'S' && x.score.总分 >= cfg.入选.S档门槛).sort(降序);",
    换: "  const S入 = 打过.filter((x) => x.tier === 'S' && x.score.总分 >= 999).sort(降序);" },
  { 名: 'C6 去掉逐源 try 隔离（坏源带走好源）', 档: 'intel/run.js',
    找: '    } catch (e) {\n      // 坏源不带走好源',
    换: '    } finally { if (false) {} } if (false) { try {} catch (e) {\n      // 坏源不带走好源' },
  { 名: '装配器抽掉「未精编」标注（静默留白）', 档: 'intel/assemble.js',
    找: "    行.push('  - *（本条未精编）*');",
    换: "    // 变异：静默留白" },
  { 名: '装配器抽掉一个区（源健康）', 档: 'intel/assemble.js',
    找: "  md.push('## 源健康');",
    换: "  md.push('## 变异掉的区');" },
  { 名: 'GT-1 A1 把追加意图改成整表重写', 档: 'server/lib/线程.js', 测: 'node test/群聊.test.js',
    找: '  const 写体 = JSON.stringify({ text: String(文) });',
    换: '  const 写体 = JSON.stringify({ text: String(文), 重写: true });' },
  { 名: 'GT-1 A2 摘掉路由侧白名单拒绝', 档: 'server/lib/路由.js', 测: 'node test/群聊.test.js',
    找: '  if (!是白名单(发言人)) return { ok: false, 拒绝: true, 因: `不在群聊白名单内：${发言人}`, 唤起: [], 应答: [] };',
    换: '  if (false) return { ok: false, 拒绝: true, 因: `不在群聊白名单内：${发言人}`, 唤起: [], 应答: [] };' },
  { 名: 'GT-1 A4 离线时偷写本地 thread 文件', 档: 'server/lib/线程.js', 测: 'node test/群聊.test.js',
    找: "  const r = await 请求JSON({ 方法: 'POST', 路径: 写路径, 体: 写体, origin: 选项.origin, 超时: 选项.超时 });\n  if (r.读不到) return r;",
    换: "  const r = await 请求JSON({ 方法: 'POST', 路径: 写路径, 体: 写体, origin: 选项.origin, 超时: 选项.超时 });\n  if (r.读不到) { require('fs').appendFileSync(require('path').join(process.env.STUDIO_ROOT, 'thread.jsonl'), String(文)); return r; }" },
  { 名: 'GT-1 B1 把 @ 路由改成广播全体', 档: 'server/lib/路由.js', 测: 'node test/群聊.test.js',
    找: "    唤起 = [坐席.按名('助理'), ...被点];",
    换: '    唤起 = 坐席.全部;' },
  { 名: 'GT-1 C1 把线程写口改成动作口', 档: 'server/lib/线程.js', 测: 'node test/群聊.test.js',
    找: "const 写路径 = '/api/relay';",
    换: "const 写路径 = '/api/act/放行';" },
  // 自启两处。这一格从前是判据真空——七条判据一条都没碰 portable，
  // 而 portable 正是本项目唯一的打包目标。下面两处变异各自对应一条硬拦：
  { 名: '自启 取路径改回 execPath（portable 下注册一条关窗即消失的路径）',
    档: 'server/lib/自启.js', 测: 'node test/自启.test.js',
    找: '  const exe = win(opts.exe || process.env.PORTABLE_EXECUTABLE_FILE || process.execPath);',
    换: '  const exe = win(opts.exe || process.execPath);' },
  // 这一条尤其要能红：删掉硬拦不会报错、不会告警，装() 照样返回 ok:true——
  // 静默错正是它最危险的地方，所以必须有判据在盯。
  { 名: '自启 删掉 %TEMP% 硬拦（静默把自启注册进临时解压目录）',
    档: 'server/lib/自启.js', 测: 'node test/自启.test.js',
    找: '    if (v === 临 || v.startsWith(临 + path.sep)) {',
    换: '    if (false) {' },
  // 编码两处。08-29 04:05 真机实测：这两处任一犯病，schtasks 就收到坏路径／坏任务名，
  // 而 dry 判据全程绿——**病只在真跑命令行那一段发作**，所以判据⑤必须真注册一次。
  { 名: '自启 跑() 去掉 chcp 65001（中文过 cmd 命令行被 GBK 化）',
    档: 'server/lib/自启.js', 测: 'node test/自启.test.js',
    找: "  const r = spawnSync('chcp 65001 >nul & ' + cmd, { shell: true, encoding: 'utf8', windowsHide: true });",
    换: "  const r = spawnSync('cmd.exe', ['/d', '/s', '/c', cmd], { encoding: 'utf8', windowsHide: true });" },
  // 互保两处。08-29 04:5x：塔那条目标在 exe 里被静默丢掉，杀塔五分钟无人来扶。
  { 名: '互保 不走计划任务，退回自己 spawn 命令',
    档: 'server/lib/互保.js', 测: 'node test/互保.test.js',
    找: '  if (目标.任务名) {',
    换: '  if (false) {' },
  { 名: '互保目标 退回 existsSync 决定要不要摆出来（静默丢边）',
    档: 'server.js', 测: 'node test/互保.test.js',
    找: "    键: '塔', 名: '瞭望塔',",
    换: "    键: '塔x', 名: '瞭望塔'," },
  // 班次额度闸两处。这道闸失效的代价不是多花钱，是制作人早上打开终端没得用——
  // 订阅是 5h/周窗口制，夜里烧穿了白天补不回来。
  { 名: '班次 读不到用量就放行（闸整个失效）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: "    return { 行: false, 因: '拒绝开班：' + 耗.因",
    换: "    return { 行: true, 因: '拒绝开班：' + 耗.因" },
  // 08-30 壳统一：导航单一事实源 + 片段模式。
  // 这一族的失效形态是「新做的页面从主屏看不见」——不报错，没人会发现，已经犯过三次。
  { 名: '壳 顶栏漏掉一个页签（新页面从标签页那侧也看不见）',
    档: 'server/render/页.js', 测: 'node test/壳.test.js',
    找: '    ${页签表.map((t) => (t.主页',
    换: '    ${页签表.slice(0, 3).map((t) => (t.主页' },
  { 名: '壳 片段模式不抽主体（整页塞进主页，两套壳叠着）',
    档: 'server.js', 测: 'node test/壳.test.js',
    找: '      const m = b.match(/<main class="wrap">([\\s\\S]*?)<\\/main>/);',
    换: '      const m = null;' },
  // 08-30 红队站住的两条重级击杀，各自的修法都要能红
  { 名: '班次 水位不看新鲜度（塔死后拿旧读数当现状，屏上跟新鲜的一样）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: '  if (!Number.isFinite(龄秒) || 龄秒 > 陈旧) {',
    换: '  if (false) {' },
  // 08-30 四类班次 + 班次页
  { 名: '班次 去掉 仅星期 判断（周末巡检天天跑，那就不是周末巡检了）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: '  if (Array.isArray(配.仅星期) && 配.仅星期.length) {',
    换: '  if (false) {' },
  { 名: '班次 「今天不跑」与「还没到点」共用一句话（屏上分不开）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: "      return { 到: false, 因: '今天不是它该跑的日子', 不该跑: true };",
    换: "      return { 到: false, 因: `还没到点（差 0 分钟）` };" },
  { 名: '班次 「断了」并进「错过」（跑到一半被杀 = 压根没开过）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: '  if (今日.开班条) {',
    换: '  if (false) {' },
  { 名: '班次 今日跑过 只认收班（跑崩一次就被重跑一次，崩三次烧三遍）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: '  return (Array.isArray(条们) ? 条们 : []).some((o) => o',
    换: "  return (Array.isArray(条们) ? 条们 : []).some((o) => o && o.型 === '收班'" },
  { 名: '班次 挑班次不剔今天跑过的（前一班的补跑窗口把后一班永远挡住）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: "    .filter((c) => c && c.启用 !== false && String(c.话 || '').trim() && !跑过(c.班次))",
    换: "    .filter((c) => c && c.启用 !== false && String(c.话 || '').trim())" },
  // 窗口水位闸：首班坐席自己找出来的洞——闸只数自己那本账，看不见真实订阅窗口烧到哪了
  { 名: '班次 读不到真实水位就放行（额度文件一没，窗口闸等于不存在）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: "  if (!w.读到) return { 行: false, 因: '拒绝开班：' + w.因",
    换: "  if (!w.读到) return { 行: true, 因: '拒绝开班：' + w.因" },
  { 名: '班次 窗口水位取第一条而不是最近一条（拿开班时的旧读数当现状）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: '  for (let i = 行.length - 1; i >= 0; i -= 1) {',
    换: '  for (let i = 0; i < 行.length; i += 1) {' },
  { 名: '班次 补跑窗口去掉上界（下午开机会莫名跑一班夜班）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: '  if (过分 > 窗) return { 到: false,',
    换: '  if (false) return { 到: false,' },
  { 名: '班次 把人在场的交互也算进班次预算（口径错，会提前掐掉夜班）',
    档: 'server/lib/班次.js', 测: 'node test/班次.test.js',
    找: "    if (!String(o.来路 || '').startsWith('班次')) continue;   // 人在场的交互不占班次预算",
    换: '    if (false) continue;' },
  // 这里一度还有一条「XML 临时文件名改回中文」的变异，实测**不红**——
  // 有 chcp 65001 在，文件名带不带中文都能注册成功。也就是说 ASCII 文件名不是承重件，
  // 只是纵深防御。留着变异会让「16 处都有判据盯着」这句话虚一格，故删。
  // 不红的变异只有两种解释：判据没覆盖，或那处改动本来就不重要。这里是后者。

  // ── 2026-08-31 批一：md.js 扩写 ──
  // 扩写前实测：设计文档 547 行里 150 行渲染错（27%）。最坏的不是"少了表格"，
  // 是**围栏里的 - 和 # 被当成列表和标题吃掉**——结构被搅乱。七条各拆一处。
  { 名: 'md 围栏不再是围栏（里面的 # 和 - 会被当成标题和列表吃掉）',
    档: 'server/render/md.js', 测: 'node --test test/md渲染.test.js',
    找: "    const 开围 = 行文.match(/^\\s{0,3}(```+|~~~+)\\s*([^\\s`]*)\\s*$/);",
    换: '    const 开围 = null;' },
  { 名: 'md 表格不认（83 行表格全掉进 <p>|）',
    档: 'server/render/md.js', 测: 'node --test test/md渲染.test.js',
    找: "    if (行文.includes('|') && i + 1 < 行.length && 是分隔行(行[i + 1])) {",
    换: '    if (false) {' },
  { 名: 'md 分隔线掉回段落',
    档: 'server/render/md.js', 测: 'node --test test/md渲染.test.js',
    找: "    if (/^\\s{0,3}(-{3,}|\\*{3,}|_{3,})\\s*$/.test(行文)) { 收到(0); 出.push(`<hr${属()}>`); continue; }",
    换: '    if (false) { 收到(0); continue; }' },
  { 名: 'md 标题退回只认 h1-h3（18 个 #### 掉进段落）',
    档: 'server/render/md.js', 测: 'node --test test/md渲染.test.js',
    找: '    const 题 = 行文.match(/^\\s{0,3}(#{1,6})\\s+(.*)$/);',
    换: '    const 题 = 行文.match(/^\\s{0,3}(#{1,3})\\s+(.*)$/);' },
  { 名: 'md 有序列表不认（1. 掉进段落）',
    档: 'server/render/md.js', 测: 'node --test test/md渲染.test.js',
    找: '    const 有序 = 行文.trim().match(/^\\d{1,9}[.)]\\s+(.*)$/);',
    换: '    const 有序 = null;' },
  { 名: 'md 不剥 BOM（一级标题静默降级成段落，编辑器里还看不见）',
    档: 'server/render/md.js', 测: 'node --test test/md渲染.test.js',
    找: "  const 全 = String(md == null ? '' : md).replace(/^\\uFEFF/, '');",
    换: "  const 全 = String(md == null ? '' : md);" },
  { 名: 'md 占位符退回可打印形式（正文里的「 C3 」被当成代码槽吃掉）',
    档: 'server/render/md.js', 测: 'node --test test/md渲染.test.js',
    找: '  return s.replace(/\\u0000(\\d+)\\u0000/g, (_, i) => 代码槽[Number(i)]);',
    换: '  return s.replace(/ C(\\d+) /g, (_, i) => 代码槽[Number(i)]);' },

  // ── 2026-08-31 批二：文稿台（文件库 · 只读）──
  // 终端**无鉴权**，而这是它的第一个写口的门。原 校档名() 至今零判据，
  // 所以这九条不只是"证明判据有效"，是这个门第一次被证明关得上。
  { 名: '文稿 校路径 不拦上跳段（../ 直接读到根外，无鉴权下最直接的那条）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: "  if (s.split('/').some((seg) => seg === '..')) return { 行: false, 因: '路径含上跳段' };",
    换: "  if (false) return { 行: false, 因: '路径含上跳段' };" },
  { 名: '文稿 校路径 不判 realpath 落根内（软链跳出根即失守）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: "  if (!在根内(真根, 真档)) return { 行: false, 因: '解析后落在根之外（软链或上跳）' };",
    换: "  if (false) return { 行: false, 因: '解析后落在根之外（软链或上跳）' };" },
  { 名: '文稿 校路径 照抄 校档名 的写法（realpath 文件而非父目录 → 新建路天然失效）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: '    真父 = 真解(path.dirname(拼));',
    换: '    真父 = path.dirname(真解(拼));' },
  { 名: '文稿 可写 不看禁写前缀（活存储放开写，runner 状态错乱且 git 还原不回）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: '  for (const 禁 of (根.禁写 || [])) {',
    换: '  for (const 禁 of []) {' },
  { 名: '文稿 可写 禁写用 includes 而不是段前缀（活区 会连坐 活区补）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: "    if (s === p || s.startsWith(p + '/')) {",
    换: '    if (s.includes(p)) {' },
  { 名: '文稿 扫记号 不挖行内代码（把说明表那四行当成四条待办）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: "    const 净 = l.replace(/`[^`]*`/g, (m) => ' '.repeat(m.length));",
    换: '    const 净 = l;' },
  { 名: '文稿 扫记号 不管围栏（示例代码里的记号被算成待办）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: '    if (在围栏) continue;',
    换: '    if (false) continue;' },
  { 名: '文稿 列举 不做目录剪枝（TK 的 1323 个 PackageCache README 涌进文件库）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: '          if (剪.has(it.name.toLowerCase())) continue;',
    换: '          if (false) continue;' },
  { 名: '文稿 读盘不剥 BOM（每存一次 BOM 搬一次家，首行标题静默降级）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: '  if (有BOM) s = s.slice(1);',
    换: '  if (false) s = s.slice(1);' },
  // 片段不带脚本 = 四个页面的前端在壳里全哑（原始流/监视/席间存照/文稿）。
  // 这个病的表现是「页面在，但不动」——不报错、不白屏，只是什么都不发生。
  { 名: '片段不把 <script> 的 src 带出来（四页前端在壳里全哑，且不报错）',
    档: 'server.js', 测: 'node --test test/壳.test.js',
    找: "        const 属 = 脚.length ? ` data-脚本=\"${脚.join(' ')}\"` : '';",
    换: "        const 属 = '';" },

  // ── 2026-08-31 批三：写口 + 锁 + 版本 ──
  // 这一批是终端**第一个写口**。此前它对外纯只读，所以下面这些不是「功能有没有做对」，
  // 是「无鉴权的机器上，任何网页能不能改你的文件」。
  { 名: '锁 租约不失效（浏览器崩了/进程被杀 → 盘上留一把谁也解不开的死锁）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: "  if (剩 <= 0) return { 态: '过期', 剩余毫秒: 0, 闲置毫秒: 现在 - 键时 };",
    换: "  if (false) return { 态: '过期', 剩余毫秒: 0, 闲置毫秒: 现在 - 键时 };" },
  { 名: '锁 闲置不降级（点了编辑就去睡 → 我一整夜动不了那份文件）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: "  if (现在 - 键时 >= 闲置毫秒) return { 态: '可抢', 剩余毫秒: 剩, 闲置毫秒: 现在 - 键时 };",
    换: "  if (false) return { 态: '可抢', 剩余毫秒: 剩, 闲置毫秒: 现在 - 键时 };" },
  { 名: '锁 可写不校令牌（谁都能写别人锁着的文件）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: '  if (!令 || 令 !== 条.令牌) return { 行: false, 因: `文件被 ${条.持有者 || \'别人\'} 锁着`, 态: t.态 };',
    换: '  if (false) return { 行: false, 因: `文件被 ${条.持有者 || \'别人\'} 锁着`, 态: t.态 };' },
  { 名: '锁 外部进程看不见（坐席与 hook 的闸失效，锁只剩装饰）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: "        if (t.态 === '持有' || t.态 === '可抢') {",
    换: '        if (false) {' },
  { 名: '草稿 只落哈希不落 base 字节（冲突时「保留我的」在数据模型里不存在）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: "        原子写(底 + '.base.md', String(基文));",
    换: '        void 基文;' },
  { 名: '版本 从净化过的文件名回读「谁写的」（班次:晨报 与 班次_晨报 撞成一个）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: '        const o = 由索引.get(f);',
    换: '        const o = null;' },
  { 名: '版本环无上界（又一处无界增长，欠账表第 10 条已经有一处了）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: '      const 删掉 = 们.slice(0, Math.max(0, 们.length - 版本上限));',
    换: '      const 删掉 = [];' },
  { 名: '告示 过期的锁也挂着（坐席每条对话都收到一堆早就没了的占用）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: "    .filter(([, c]) => 判态(c, 现在).态 !== '过期')",
    换: '    .filter(() => true)' },
  { 名: '写闸 放行 text/plain（那条 no-cors 攻击直接打进来）',
    档: 'server/lib/写闸.js', 测: 'node --test test/写闸.test.js',
    找: '  if (!/^application\\/json\\b/.test(类型)) {',
    换: '  if (false) {' },
  { 名: '写闸 缺 Origin 就放行（"判不出来就放行"＝没有闸）',
    档: 'server/lib/写闸.js', 测: 'node --test test/写闸.test.js',
    找: "  if (!来源) return { 行: false, 码: 403, 因: '缺 Origin' };",
    换: "  if (!来源) return { 行: true, 码: 200, 因: '缺 Origin' };" },
  { 名: '写闸 令牌台无上限（常驻整天开着 = 一处内存泄漏）',
    档: 'server/lib/写闸.js', 测: 'node --test test/写闸.test.js',
    找: '      while (们.size > 令牌上限) 们.delete(们.keys().next().value);',
    换: '      void 令牌上限;' },
  { 名: '写口 冲突时照样覆盖（制作人 25 分钟的手工标注静默消失）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: '    if (!基纹 || 基纹 !== 盘纹) {',
    换: '    if (false) {' },
  { 名: '写口 落盘不还原换行（一次保存 547 行全变改动行，标了哪几处被淹掉）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: "    if (原 && 原.换行 === 'crlf') s = s.replace(/\\n/g, '\\r\\n');",
    换: '    void 原;' },
  { 名: '写口 落盘不还原 BOM',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: "    if (原 && 原.有BOM) s = '\\uFEFF' + s;",
    换: '    void 0;' },
  { 名: '写口 不落版本（改了没有回头路，且坐席的改动在历史里隐形）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: "    const 版 = 锁台.存版(位.根键, 位.相对, 文, String(req.body.谁 || '制作人'));",
    换: "    const 版 = { 版: '没存' };" },
  { 名: '写口 不判写权（活存储也能写，runner 状态错乱且 git 还原不回）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: '      if (!写.行) { res.status(403).json({ 行: false, 因: 写.因 }); return null; }',
    换: '      void 写;' },
  { 名: '解锁请求不进人闸队列（我在等你解锁，而你屏上看不到）',
    档: 'server.js', 测: 'node --test test/写口.test.js',
    找: '  const 本地 = 文稿闸债();',
    换: '  const 本地 = [];' },

  // ── 2026-08-31 批四：编辑器 ──
  { 名: '存盘后清掉 base 而不是重置（第二次冲突拿不到比较基准，「保留我的」退化成盲覆盖）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: '    锁台.重置基(位.根键, 位.相对, 文, 锁lib.指纹(文));',
    换: '    锁台.清草(位.根键, 位.相对);' },
  // 这里一度有一条「重新取锁不重设 base」的变异，2026-08-31 验收复核后**实测不红**。
  // 原因是那次复核之后补的两处改动把它顶掉了：存草() 现在会在基指纹变化时重写 base，
  // 而 /api/doc/save 的 能三路 又加了「指纹(base) === 基纹」的校验。
  // 于是取锁时那次重设不再是正确性的承重件——少了它最坏也只是 能三路 退化成 false
  // （诚实地说「给不出三路」），不会给出一张指着错地方的差异图。
  // 不红的变异只有两种解释：判据没覆盖，或那处改动本来就不重要。这里是后者。
  // 那一行留着是纵深（少一次退化），不是承重，所以不为它硬造一条变异。
  { 名: '过时草稿不带自己的基准回来（载入后存盘静默盖掉别人的改动，连冲突框都不弹）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: '        ? { 文: 草.文, 时: 草.时, 同源: 草.基指纹 === 纹, 基指纹: 草.基指纹, 基文: 草.基文 }',
    换: '        ? { 文: 草.文, 时: 草.时, 同源: 草.基指纹 === 纹 }' },
  { 名: '文件库不排掉文稿台自己的工作目录（版本历史涌进左栏，存一次多一条）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: '          if (排.some((p) => g === p || g.startsWith(p + \'/\'))) continue;',
    换: '          void 排;' },

  // ── 2026-08-31 验收复核确证的六条，各配一处变异 ──
  // 「草稿裸写不原子」这条变异**做不出来**，明写在这里而不是含糊过去：
  // 原子写的收益只在「进程死在写到一半」那一刻显现，而那一刻在同进程的判据里演不出来。
  // 守⑭e 能验的只是「不留 .tmp」——把原子写改成裸写反而没有 .tmp，判据会绿。
  // 真正兜住这条病的是 守⑭c（**半截草稿不许被当成完整的**），
  // 它的承重件是 取草() 里那句 草纹 校验，由下面那条变异盯着。
  // 所以：原子写记为**结构性防御、无行为判据**——盲区明写，不假装覆盖。
  { 名: '取草不校验字节（半个 markdown 看着仍像一份 markdown）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: '        if (稿 != null && 元.草纹 && 指纹(稿) !== 元.草纹) { 稿 = null; 损 = true; }',
    换: '        void 元;' },
  { 名: '重置基 直接删草稿而不是留孤儿（元信息坏了就把完整草稿销毁）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: "          fs.renameSync(底 + '.draft.md', `${底}.orphan-${Date.now()}.md`);",
    换: "          fs.unlinkSync(底 + '.draft.md');" },
  { 名: '存草 的 base 退回 existsSync 守卫（base 永不更新，冲突面板拿两代前的版本画差异）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: "      if (基文 != null && (!fs.existsSync(底 + '.base.md') || !旧元 || 旧元.基指纹 !== 基指纹)) {",
    换: "      if (基文 != null && !fs.existsSync(底 + '.base.md')) {" },
  { 名: '锁键不折叠大小写（同一份文件裂出第二把「独占」锁）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: "const 键 = (根键, 相对) => `${根键}/${String(相对).replace(/\\\\/g, '/')}`.toLowerCase();",
    换: "const 键 = (根键, 相对) => `${根键}/${String(相对).replace(/\\\\/g, '/')}`;" },
  // 这条变异的方向 2026-08-31 晚翻了一次：闸接上之前它防「声称有闸而闸不存在」，
  // 接上之后防的是「闸接上了却不告诉坐席，它被挡了不知道为什么、下一步该干什么」。
  { 名: '告示不说清有机器闸（坐席被挡了却不知道为什么，也不知道往哪走）',
    档: 'server/lib/文锁.js', 测: 'node --test test/文锁.test.js',
    找: "    + '\\n（**这条有机器闸**：Edit/Write 会被 PreToolUse 拦下并记一条解锁请求进他的人闸队列。'",
    换: "    + '\\n（别写。'" },
  { 名: '冲突时不先存盘上那版（「保留我的」的承诺每一次都是假的）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: "        锁台.存版(位.根键, 位.相对, 现.文, '盘上原版·外部写入');",
    换: '        void 现;' },
  { 名: '能三路 只判 base 非空（假的 true 会把「盲覆盖」那条警告抑制掉）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: '      const 基对 = !!(草.有 && 草.基文 != null && 锁lib.指纹(草.基文) === 基纹);',
    换: '      const 基对 = !!(草.有 && 草.基文 != null);' },
  { 名: '基指纹为空就跳过冲突比对（不经前端的调用方一次静默全覆盖）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: '    if (!基纹 || 基纹 !== 盘纹) {',
    换: '    if (基纹 && 基纹 !== 盘纹) {' },
  // ── 2026-08-31 晚：占用闸接上 ──
  { 名: '坐席的 PreToolUse 闸被摘掉（外部可写() 退回零调用点，告示又变成一句空话）',
    档: 'server.js', 测: 'node --test test/写口.test.js',
    找: '    hooks: {\n      PreToolUse: [{',
    换: '    不接闸: {\n      PreToolUse: [{' },
  { 名: '闸拦下之后不记解锁请求（坐席被挡了，而制作人屏上没有任何痕迹）',
    档: 'server.js', 测: 'node --test test/写口.test.js',
    找: "                文稿台.请求解锁(x.键.slice(0, i), x.键.slice(i + 1), '总监',",
    换: "                void ((a, b, c) => 0)(x.键.slice(0, i), x.键.slice(i + 1), '总监'," },
  { 名: '写手闸 把读也拦了（坐席读不了锁着的文件就答不了话）',
    档: 'server/lib/写手闸.js', 测: 'node --test test/写手闸.test.js',
    找: "  if (!写工具.has(String(工具名))) return { 决: 'allow', 因: '不是写工具', 挡住的: [] };",
    换: '  if (false) return {};' },
  { 名: '写手闸 查锁抛异常时改成拒（把小概率碰撞换成大概率瘫痪）',
    档: 'server/lib/写手闸.js', 测: 'node --test test/写手闸.test.js',
    找: '    try { r = 查锁(p); } catch (e) { continue; }   // 闸自己坏了不拖垮坐席',
    换: "    try { r = 查锁(p); } catch (e) { r = { 行: false, 因: '闸自己坏了' }; }" },

  // ── 2026-09-01 · 归类（评审：此前零判据覆盖，掏空它 308 条仍全绿）──
  { 名: '归类塌成单桶（分类功能整个拆掉，屏上每一组的标题都成了摆设）',
    档: 'server/lib/文稿.js', 测: 'node --test test/归类.test.js',
    找: "    if ((c.配 || []).some((re) => re.test(s))) return c.键;",
    换: '    void s;' },
  { 名: '归类退回只认路径段开头（TK 那种「XX-方案.md」全漏，实测 33/73）',
    档: 'server/lib/文稿.js', 测: 'node --test test/归类.test.js',
    找: '    if (c.名词 && 词命(词, c.名词)) return c.键;',
    换: '    void 词;' },
  { 名: '词命去掉长度限制（施工令被「评审」两个字从规章里偷走）',
    档: 'server/lib/文稿.js', 测: 'node --test test/归类.test.js',
    找: '  (k) => t === k || t.endsWith(k) || (t.startsWith(k) && t.length <= k.length + 2)));',
    换: '  (k) => t.includes(k)));' },
  { 名: 'memory 根不整根归记忆库（我维护的档混进他要改的那一堆）',
    档: 'server/lib/文稿.js', 测: 'node --test test/归类.test.js',
    找: "  if (根键 === 'memory') return 'jiyi';",
    换: '' },
  { 名: '类别名改回「在办文稿」（承诺时效性，而规则只看体裁词）',
    档: 'server/lib/文稿.js', 测: 'node --test test/归类.test.js',
    找: "    键: 'zaiban', 名: '方案与评审',",
    换: "    键: 'zaiban', 名: '在办文稿'," },

  // ── 2026-08-31 夜 · 两条致命项（内部评审在起火前 15 分钟查出）──
  { 名: '/api/events 用 UTC 月拼档名（每月 1 号本地 00:00-07:59 静默显示上个月）',
    档: 'server.js', 测: 'node --test test/本地月.test.js',
    找: "  const 月 = require('./server/lib/读数').本地月();",
    换: "  const 月 = new Date().toISOString().slice(0, 7);" },
  { 名: '本地月退回 UTC 切片（写侧按本地分档，读侧按 UTC 找档）',
    档: 'server/lib/读数.js', 测: 'node --test test/本地月.test.js',
    找: "const 本地月 = (d = new Date()) =>\n  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;",
    换: 'const 本地月 = (d = new Date()) => d.toISOString().slice(0, 7);' },
  { 名: '监视.js 留着那行没删的守卫（未声明标识符，整页脚本从第 17 行起全不执行）',
    档: 'public/监视.js', 测: 'node --test test/前端起手.test.js',
    找: "  const 取脚 = () => document.getElementById('wfoot');",
    换: "  const 取脚 = () => document.getElementById('wfoot');\n  if (!网) return;" },
  { 名: 'index.html 漏挂一个脚本（那一段静默不跑，页面看着照常）',
    档: 'public/index.html', 测: 'node --test test/前端起手.test.js',
    找: '<script src="视图.js"></script>',
    换: '<script src="不存在的.js"></script>' },

  // ── 2026-08-31 夜 · 顶栏读数 ──
  { 名: '登录剩余按小时取整（40 分钟写成「登录 0h」，读起来就是已经没了）',
    档: 'public/顶况.js', 测: 'node --test test/顶况.test.js',
    找: "    if (m < 90) return `登录 ${Math.round(m)} 分`;",
    换: '    if (m < 90) return `登录 ${Math.floor(m / 60)}h`;' },
  { 名: '没读到剩余分钟被写成"已过期"（把不知道说成确定的坏消息）',
    档: 'public/顶况.js', 测: 'node --test test/顶况.test.js',
    找: "    if (剩余分 === null || 剩余分 === undefined || 剩余分 === '') return '登录—';",
    换: '' },
  { 名: '额度只报周窗口（当下真正会把人拦住的 5 小时窗口一个字都没有）',
    档: 'public/app.js', 测: 'node --test test/顶况.test.js',
    找: "  const r = 顶况文.额度文((q.claude || {}).windows);",
    换: "  const r = 顶况文.额度文(((q.claude || {}).windows || []).filter((w) => w.label === '周'));" },
  { 名: '低水位也摆重置时刻（197px，占顶况三分之一，而那时它没人会用）',
    档: 'public/顶况.js', 测: 'node --test test/顶况.test.js',
    找: '    const 紧 = 表.filter((w) => Number(w.pct) >= 阈);',
    换: '    const 紧 = 表.slice();' },
  { 名: '快撞顶时反而不摆重置时刻（这时"什么时候恢复"才是那个问题）',
    档: 'public/顶况.js', 测: 'node --test test/顶况.test.js',
    找: '    if (紧.length) {',
    换: '    if (false) {' },
  { 名: 'index.html 不引 顶况.js（app.js 顶层解构就炸，整个前端不跑）',
    档: 'public/index.html', 测: 'node --test test/顶况.test.js',
    找: '<script src="顶况.js"></script>',
    换: '' },

  // ── 2026-08-31 夜 · 私聊落地（在这之前它整条都是皮）──
  { 名: '席不发给服务端（私聊退回换皮：同一个会话、同一个人设、同一份记忆）',
    档: 'public/app.js', 测: 'node --test test/私聊.test.js',
    找: '      body: JSON.stringify(私聊席 ? { 话: 全, 席: 私聊席 } : { 话: 全 }),',
    换: '      body: JSON.stringify({ 话: 全 }),' },
  { 名: '答话永远署名总监（跟屏幕顶上那行「私聊 X」互相打脸）',
    档: 'public/app.js', 测: 'node --test test/私聊.test.js',
    找: "  const 格 = 加话(私聊席 || '总监', '');",
    换: "  const 格 = 加话('总监', '');" },
  { 名: '400 的报错被 SSE 解析器吃掉（屏上只剩一句「（无输出）」）',
    档: 'public/app.js', 测: 'node --test test/私聊.test.js',
    找: '    if (!res.ok) {',
    换: '    if (false) {' },
  { 名: '未接模型的席位照样进私聊（顶边亮起、写着有独立记忆，然后没人应）',
    档: 'public/app.js', 测: 'node --test test/私聊.test.js',
    找: '  if (席况.has(名) && !席况.get(名)) {',
    换: '  if (false) {' },
  { 名: '未接的席位做成 disabled（点了完全没反应，正是这轮在抓的病）',
    档: 'public/app.js', 测: 'node --test test/私聊.test.js',
    找: "      + (名 === '制作人' ? ' disabled' : '')",
    换: "      + (名 === '制作人' || 未接 ? ' disabled' : '')" },
  { 名: '服务端不验席（未接模型的席位从别的入口照样能开一条线）',
    档: 'server.js', 测: 'node --test test/私聊.test.js',
    找: '    if (!s.接模型) return res.status(400).json({ error: `${席名} 还没接模型，说了没人应` });',
    换: '    void 0;' },
  { 名: '席名不认识就当群聊放过（点了个不存在的人，聊得很开心）',
    档: 'server.js', 测: 'node --test test/私聊.test.js',
    找: '    if (!s) return res.status(400).json({ error: `名单里没有「${席名}」这一席` });',
    换: '    if (!s) { 席 = null; }' },
  { 名: '会话不按席分家（私聊接上群里那条线，或反过来把群覆盖掉）',
    档: 'server.js', 测: 'node --test test/私聊.test.js',
    找: '  const 续 = 读会话(席 && 席.名);',
    换: '  const 续 = 读会话();' },
  { 名: '席名不洗就进文件名（../ 能拼出终端根之外的路径）',
    档: 'server.js', 测: 'node --test test/私聊.test.js',
    找: "const 席档名 = (席) => String(席 || '').replace(/[^一-龥A-Za-z0-9_-]/g, '').slice(0, 24);",
    换: "const 席档名 = (席) => String(席 || '').slice(0, 24);" },
  { 名: '洗空后仍拼席名档（生成一个半截的 .session-.json）',
    档: 'server.js', 测: 'node --test test/私聊.test.js',
    找: '  return s ? path.join(终端根, `.session-${s}.json`) : 会话档;',
    换: '  return path.join(终端根, `.session-${s}.json`);' },
  { 名: '人设不接进系统提示（八条私线长得一模一样）',
    档: 'server.js', 测: 'node --test test/私聊.test.js',
    找: '    ...(opt.席 && opt.人设 ? {',
    换: '    ...(false ? {' },
  { 名: '私聊用量混进群账（看不出是哪条线在烧额度）',
    档: 'server.js', 测: 'node --test test/私聊.test.js',
    找: '        记用量(席 ? `${来路}·${席.名}` : 来路, m);',
    换: '        记用量(来路, m);' },

  // ── 2026-08-31 夜 · 左栏分堆 ──
  { 名: '左栏不分堆（61 个按钮摊平，四千像素的墙原样还回去）',
    档: 'public/闸分组.js', 测: 'node --test test/闸分组.test.js',
    找: "        const k = d.闸号 || '其它';",
    换: "        const k = '全部';" },
  { 名: '久档退回三档（13 天那条与 5 天那堆同色，染色白染）',
    档: 'public/闸分组.js', 测: 'node --test test/闸分组.test.js',
    找: '    return x >= t * 7 ? 3 : x >= t * 3 ? 2 : x >= t ? 1 : 0;',
    换: '    return x >= t * 3 ? 2 : x >= t ? 1 : 0;' },
  { 名: '组头丢掉动作（24 单同一个动作这件事又只剩 title 里知道）',
    档: 'public/闸分组.js', 测: 'node --test test/闸分组.test.js',
    找: "动: d.指引 || d.动作键 || ''",
    换: "动: ''" },
  { 名: '同样大的组顺序不定（每 5 秒自己重排，眼睛跟不上）',
    档: 'public/闸分组.js', 测: 'node --test test/闸分组.test.js',
    找: '(y.项.length - x.项.length) || String(x.号).localeCompare(String(y.号))',
    换: 'y.项.length - x.项.length' },
  { 名: '机制下标不偏移（点第 N 条机制，带上来的是第 N 张单）',
    档: 'public/闸分组.js', 测: 'node --test test/闸分组.test.js',
    找: '型表.get(k).push({ d, i: 单们.length + i });',
    换: '型表.get(k).push({ d, i });' },
  { 名: '全组同档仍上底色（36 单全红等于没红）',
    档: 'public/闸分组.js', 测: 'node --test test/闸分组.test.js',
    找: '齐: h.length > 1 && 档.size === 1 && [...档][0] >= 2,',
    换: '齐: false,' },
  { 名: '折叠默认无视记忆（他展开的每轮轮询又被收回去）',
    档: 'public/闸分组.js', 测: 'node --test test/闸分组.test.js',
    找: '    if (有记) return 记 === true;',
    换: '' },
  { 名: '筛窄后仍替他收起（刚筛完还要再点一次才看得见）',
    档: 'public/闸分组.js', 测: 'node --test test/闸分组.test.js',
    找: "    if (筛 && 筛 !== '全') return false;",
    换: '' },
  { 名: '数字键按闸表下标取（折起来的那些也能被带上，带的不是你指的那条）',
    档: 'public/app.js', 测: 'node --test test/闸分组.test.js',
    找: "const 见 = [...$('闸列').querySelectorAll('.闸')].filter((x) => x.offsetParent !== null);",
    换: '上带(Number(e.key) - 1); const 见 = [];' },
  { 名: 'index.html 不引 闸分组.js（左栏在 self.闸分组 上炸成空白）',
    档: 'public/index.html', 测: 'node --test test/闸分组.test.js',
    找: '<script src="闸分组.js"></script>',
    换: '' },
  // ── 2026-08-31 晚 · UI 巡礼 ──
  { 名: '事种 抹掉所有数字（额度余额 10000→10 被折成一行，真值被吃掉）',
    档: 'public/事流.js', 测: 'node --test test/事件折叠.test.js',
    找: "  const 计数器键 = /\\b(seq|序号|次序|no|id)(\\s*[=:]\\s*)\\d+/gi;",
    换: "  const 计数器键 = /\\d[\\d.,:]*/g;" },
  { 名: '不认上游折过的 次（服务端在大窗口上折掉的那些凭空少了）',
    档: 'public/事流.js', 测: 'node --test test/事件折叠.test.js',
    找: '      const 本次 = Number.isFinite(e.次) && e.次 > 0 ? e.次 : 1;',
    换: '      const 本次 = 1;' },
  { 名: '折叠跨过中间插进来的事（心跳×20→失败→心跳×20 被抹成一条，时序丢了）',
    档: 'public/事流.js', 测: 'node --test test/事件折叠.test.js',
    找: '      const 尾 = 出[出.length - 1];',
    换: '      const 尾 = 出.find((x) => x.种 === 种);' },
  { 名: '监视页的清单又用回本轮增量（「N 条在等你」配一个空列表）',
    档: 'server/routes/监视.js', 测: 'node --test test/监视取数.test.js',
    找: "    const 新 = (g.数.样 || g.数.条 || []).filter((e) => e && String(e.t || '') > 水).slice(-出).reverse();",
    换: "    const 新 = (g.数.条 || []).filter((e) => e && String(e.t || '') > 水).slice(-出).reverse();" },
  { 名: '样本环不跨轮（第二轮起清单就空了，而这台机器整天不关）',
    档: 'server/lib/监视取数.js', 测: 'node --test test/监视取数.test.js',
    找: '      样 = 旧样.concat(超).slice(-样本上限);',
    换: '      样 = 超.slice(-样本上限);' },
  { 名: '页脚钟退回 UTC（本地 23:52 显示 15:50，比屏上别的钟早八小时）',
    档: 'server/lib/监视取数.js', 测: 'node --test test/监视取数.test.js',
    找: '    于本地: `${p2(d.getHours())}:${p2(d.getMinutes())}:${p2(d.getSeconds())}`,',
    换: '    于本地: d.toISOString().slice(11, 19),' },
  { 名: '记号统计 只扫可写（先标后变只读的那些，记号凭空消失）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: '    const 根 = 根路[it.根];\n    if (!根) { it.记 = null; continue; }',
    换: '    if (!it.可写) { it.记 = null; continue; }\n    const 根 = 根路[it.根];\n    if (!根) { it.记 = null; continue; }' },
  { 名: '记号缓存不看 mtime（文件改了屏上还说它没记号）',
    档: 'server/lib/文稿.js', 测: 'node --test test/文稿.test.js',
    找: '    if (旧 && 旧.改于 === it.改于) { it.记 = 旧.记; continue; }',
    换: '    if (旧) { it.记 = 旧.记; continue; }' },
  { 名: '文稿.css 往裸 .视图 上写布局（overflow:hidden 漏给五页，全都滚不动）',
    档: 'public/文稿.css', 测: 'node --test test/壳.test.js',
    找: 'body.页:has(.稿容), .视图:has(.稿容) {',
    换: 'body.页, .视图 {' },

  { 名: 'version-keep 不校锁（谁都能往版本环里塞东西）',
    档: 'server/routes/文稿页.js', 测: 'node --test test/写口.test.js',
    找: "    const 判 = 锁lib.可写(锁台.条(位.根键, 位.相对), String(req.body.令牌 || ''));\n    if (!判.行) return res.status(409).json({ 行: false, 因: 判.因 });\n    const v = 锁台.存版(",
    换: '    const v = 锁台.存版(' },
];

const 跑 = (命令 = 'node test/m1a.test.js') => {
  try {
    const out = cp.execSync(命令, { cwd: 根, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    return { 红: false, 尾: out.trim().split('\n').pop().trim() };
  } catch (e) {
    const 全 = String(e.stdout || '') + String(e.stderr || '');
    const m = 全.match(/✗[^\n]*/) || 全.match(/AssertionError[^\n]*/);
    return { 红: true, 尾: (m ? m[0] : '(未捕获)').replace(/\s+/g, ' ').slice(0, 76) };
  }
};

const 判据命令 = [...new Set(变异.map((m) => m.测 || 'node test/m1a.test.js'))];
const 基线 = 判据命令.map((命令) => ({ 命令, ...跑(命令) }));
for (const b of 基线) console.log('基线:', b.命令, b.红 ? '✗ 变异前就红 —— 先修' : '✓ 绿 ' + b.尾);
if (基线.some((b) => b.红)) process.exit(1);

let 全过 = true;
for (const m of 变异) {
  const p = path.join(根, m.档);
  const 原 = fs.readFileSync(p, 'utf8');
  if (!原.includes(m.找)) { console.log('  ⚠', m.名, '— 锚点没命中，判据未被证明'); 全过 = false; continue; }
  fs.writeFileSync(p, 原.replace(m.找, m.换), 'utf8');
  const r = 跑(m.测);
  fs.writeFileSync(p, 原, 'utf8');
  const 还原ok = fs.readFileSync(p, 'utf8') === 原;
  console.log(' ', r.红 ? '✓' : '✗', m.名, '→', r.红 ? '翻红：' + r.尾 : '**判据没红——它没在验这件事**', 还原ok ? '' : '（还原失败！）');
  if (!r.红 || !还原ok) 全过 = false;
}

const 收尾 = 判据命令.map((命令) => ({ 命令, ...跑(命令) }));
for (const b of 收尾) console.log('\n还原后复跑:', b.命令, b.红 ? '✗ 仍红' : '✓ 绿 ' + b.尾);
console.log(全过 && !收尾.some((b) => b.红)
  ? `自证能红：全部通过 —— ${变异.length} 处实现各自都有判据盯着`
  : '自证能红：有未通过项，判据不合格');
process.exit(全过 && !收尾.some((b) => b.红) ? 0 : 1);
